### ISSUE TITLE
Insert user prompt along with the tldr request

### ISSUE THREAD

**Issue by gt5772b** [meetbryce/open-source-slack-ai#13]
**Is your feature request related to a problem? Please describe.**

The problem is there is no control over the output that is given.  The tool will respond with its best guess of what the important details are to summarize and often either chooses the wrong details or chooses too many details.

**Describe the solution you'd like**

I would like to provide a prompt along with the request that tells the tool what I'd like it to do with the summary that it is providing.  For example, I could tell the prompt to return only slack entries that were from a certain person, or only entries that pertain to a certain subject. 

**Describe alternatives you've considered**

An alternative would be to copy the output to a GPT and ask it to perform the task that I'd like, but the original data may have been compromised to the point where the result does not perform what I need

**Additional context**

N/A

**Comment by meetbryce** [comment]
This makes a lot of sense and will hopefully be something we can work on soon!

**Comment by gt5772b** [comment]
Awesome, thanks for your consideration!

**Comment by meetbryce** [comment]
Will be including the original prompt in the response so that it can be easily referenced or copy and pasted for reuse.
